apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: gateway-operator
build:
  artifacts:
  - image: gateway-operator
    jib: {}
    #buildpacks:
    #  builder: gcr.io/buildpacks/builder:v1
deploy:
  kubectl:
    manifests:
    - k8s/springcloudgatewayrouteconfig.yaml
    - k8s/clusterrole.yaml
    - k8s/clusterrolebinding.yaml
    - k8s/serviceaccount.yaml
    - k8s/deployment.yaml
    - k8s/service.yaml