apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gateway-operator-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gateway-operator-view
subjects:
  - kind: ServiceAccount
    name: gateway-operator
    namespace: default