apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-operator
  namespace: default
  labels:
    app.kubernetes.io/name: gateway-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway-operator
    spec:
      serviceAccountName: gateway-operator
      containers:
        - name: gateway-operator
          image: gateway-operator
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1"
