apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: springcloudgatewayrouteconfigs.k8s.jpoint.ru
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: k8s.jpoint.ru
  # list of versions supported by this CustomResourceDefinition
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: springcloudgatewayrouteconfigs
    # singular name to be used as an alias on the CLI and for display
    singular: springcloudgatewayrouteconfig
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: SpringCloudGatewayRouteConfig
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - scgrc
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                routes:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      uri:
                        type: string
                      predicates:
                        type: array
                        items:
                          type: string
                      filters:
                        type: array
                        items:
                          type: string
            status:
              type: object
              properties:
                status:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: State
          type: string
          jsonPath: .status.status