apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore
  namespace: default
  labels:
    app.kubernetes.io/name: petstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: petstore
  template:
    metadata:
      labels:
        app.kubernetes.io/name: petstore
    spec:
      containers:
        - name: petstore
          image:  localhost:5001/swaggerapi/petstore
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1"
