apiVersion: v1
kind: Service
metadata:
  name: petstore
  namespace: default
  labels:
    app.kubernetes.io/name: petstore
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
  selector:
    app.kubernetes.io/name: petstore
